# Database Configuration
spring.jpa.hibernate.ddl-auto=update
spring.datasource.password=[Enter your password]
spring.datasource.username=[Enter Your username]
spring.datasource.url=jdbc:postgresql://localhost:5432/TestDB
spring.datasource.driver-class-name=org.postgresql.Driver

server.port=8081